### ISSUE TITLE
BUG: nil dereference on error case

### ISSUE THREAD

**Issue by jallen-cse** [brendan-ward/mbtiles-go#5]
Hello & thanks for the project,

I can reproduce a nil pointer dereference by attempting to open a file that is not valid MBTiles format.

```sh
# create an invalid mbtiles file
dd if=/dev/zero of=invalid.mbtiles bs=1M count=1
```

```go
package main

import "github.com/brendan-ward/mbtiles-go"

func main() {
    mbtiles.Open("invalid.mbtiles")
}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x49d497]

goroutine 1 [running]:
crawshaw.io/sqlite.(*Stmt).Finalize(0x0)
        /path/to/go/pkg/mod/crawshaw.io/sqlite@v0.3.2/sqlite.go:570 +0x17
github.com/brendan-ward/mbtiles-go.validateRequiredTables(0x28d167e5?)
        /path/to/go/pkg/mod/github.com/brendan-ward/mbtiles-go@v0.1.0/mbtiles.go:266 +0x143
github.com/brendan-ward/mbtiles-go.Open({0x5a9a72, 0xc})
        /path/to/go/pkg/mod/github.com/brendan-ward/mbtiles-go@v0.1.0/mbtiles.go:83 +0x2e8
main.main()
        /path/to/main.go:8
exit status 2
```

The issue is at [mbtiles.go line 273](https://github.com/brendan-ward/mbtiles-go/blob/6c48cea51706c5df7ec431b1c785f61aba888d0f/mbtiles.go#L273).

```go
query, _, err := con.PrepareTransient("SELECT count(*) as c FROM sqlite_master WHERE name in ('tiles', 'metadata')")
defer query.Finalize()

if err != nil {
	return err
}
```

The `sqlite.Con.PrepareTransient` return values are not checked before `defer`ring `query.Finalize`.

Looking around, I see this bug in 3 places total:
 - [mbtiles.go line 273](https://github.com/brendan-ward/mbtiles-go/blob/6c48cea51706c5df7ec431b1c785f61aba888d0f/mbtiles.go#L273)
 - [mbtiles.go line 294](https://github.com/brendan-ward/mbtiles-go/blob/6c48cea51706c5df7ec431b1c785f61aba888d0f/mbtiles.go#L294)
 - [mbtiles.go line 339](https://github.com/brendan-ward/mbtiles-go/blob/6c48cea51706c5df7ec431b1c785f61aba888d0f/mbtiles.go#L339)

**Comment by brendan-ward** [comment]
Resolved by #6
