### ISSUE TITLE
use in memory database

### ISSUE THREAD

**Issue by pete911** [brendan-ward/mbtiles-go#8]
Hi, we have very specific use case, our mbitles file is relatively small and we have to handle loads of traffic. Current sqlite database adds too much overhead (disk/iops). We would like to have an option to run DB in memory. Something like adding extra function:
```
func OpenInMemory("testdata/geography-class-jpg.mbtiles") {
...
source, err := Open("testdata/geography-class-jpg.mbtiles")
...
conn, err := source.BackupToDB("", ":memory:")
...
}
```
I don't mind creating PR if you are ok with this addition. Thanks for the project.

**Comment by brendan-ward** [comment]
Seems reasonable; a PR would be welcome.

**Comment by pete911** [comment]
@brendan-ward pls have a look at #9 PR. I have moved some code to separate functions, so it can be reused by `OpenInMemory` option. Let me know what you think.
